### ISSUE TITLE
网易的workflow不可用

### ISSUE THREAD

**Issue by 1900forever** [zhuziyi1989/tools#1]
Starting debug for 'NetEase News'

[2017-04-17 18:33:04][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "neteasenews.py", line 53, in <module>
    output(sys.argv[1])
  File "neteasenews.py", line 38, in output
    workflows = get_cache()
  File "neteasenews.py", line 30, in get_cache
    set_cache()
  File "neteasenews.py", line 15, in set_cache
    html = requests.get('http://c.m.163.com/nc/article/headline/T1348647853363/0-20.html').json()
  File "/Volumes/Files/Dropbox/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.50ECA2C4-0F54-46A9-8B80-88E8DA310A76/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by zhuziyi1989** [comment]
没有更新了。

> Starting debug for 'NetEase News'
> 
> [2017-04-17 18:33:04][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last): File "neteasenews.py", line 53, in output(sys.argv[1]) File "neteasenews.py", line 38, in output workflows = get_cache() File "neteasenews.py", line 30, in get_cache set_cache() File "neteasenews.py", line 15, in set_cache html = requests.get('http://c.m.163.com/nc/article/headline/T1348647853363/0-20.html').json() File "/Volumes/Files/Dropbox/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.50ECA2C4-0F54-46A9-8B80-88E8DA310A76/requests/models.py", line 741, in json return json.loads(self.text, **kwargs) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads return _default_decoder.decode(s) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode raise ValueError("No JSON object could be decoded") ValueError: No JSON object could be decoded
